export const WORKSPACE_DIR = "workspace";

export const WORKSPACE_FOLDERS = [
  "sources/cvs",
  "sources/linkedin",
  "sources/github",
  "sources/project-notes",
  "sources/recommendations",
  "sources/certificates",
  "sources/markdown",
  "sources/pdf",
  "sources/docx",
  "sources/jobs",
  "kb",
  "kb/extracted-text",
  "outputs/reports",
  "outputs/changelogs",
  "targets/roles",
  "targets/jobs",
  "role-profiles",
  "config",
  "logs"
];

export const PUBLIC_SAFETY_RULES = [
  "Every public claim must be supported by evidence IDs.",
  "Only approved, resume-ready claims are eligible for trusted matching or verbatim public output.",
  "Generic-only evidence may support generalized wording but must not be emitted verbatim.",
  "Do not include private emails, phone numbers, tokens, secrets, or credentials in generated public outputs.",
  "Do not include absolute local filesystem paths in generated public outputs.",
  "Unknown visibility should be reviewed before public use.",
  "Private and sensitive sources can inform internal evidence but should not be quoted publicly by default.",
  "Low-confidence claims must be marked needs confirmation.",
  "Do not invent users, revenue, team size, adoption, or performance metrics."
];

export const KNOWN_TECHNOLOGIES = [
  "JavaScript",
  "TypeScript",
  "React",
  "React Native",
  "Expo",
  "Node.js",
  "Vue.js",
  "Angular",
  "Python",
  "Java",
  "Spring",
  "Docker",
  "Kubernetes",
  "Supabase",
  "PostgreSQL",
  "Firebase",
  "TensorFlow.js",
  "AI",
  "LLM",
  "GitHub",
  "GitHub Projects",
  "Jira",
  "Linear",
  "Trello",
  "Notion",
  "Figma",
  "Google Analytics",
  "Excel",
  "Google Sheets",
  "Slack",
  "Confluence",
  "AWS",
  "Azure",
  "CI/CD",
  "REST",
  "API"
];

export const KNOWN_DOMAINS = [
  "telecom",
  "telecommunications",
  "EdTech",
  "education",
  "assessment",
  "healthcare",
  "manufacturing",
  "government",
  "SaaS",
  "startup",
  "AI",
  "mobile",
  "AR",
  "ERP",
  "CRM",
  "payments",
  "developer tooling",
  "platform",
  "enterprise"
];
